### ISSUE TITLE
Incorrect generation issue

### ISSUE THREAD

**Issue by damiengarbarino** [marklagendijk/WinLess#2]
Winless v1.3.0

When using the following pseudo class

.opacity(@op){
    opacity:@op/100;
    filter:alpha(opacity=@op);
}

If I use this pseudo in several places of the same file, only the first parameter is used in filter:alpha(opacity=xx);

I have a simple test case:

.opacity(@op){
    opacity:@op/100;
    filter:alpha(opacity=@op);
}

.test0 {
 .opacity(0);
}

.test1 {
 .opacity(90);
}

.test2 {
 .opacity(70);
}

.test3 {
 .opacity(0);
}

Generates ===>

.test0 {
  opacity: 0;
  filter: alpha(opacity=0);
}
.test1 {
  opacity: 0.9;
  filter: alpha(opacity=0);
}
.test2 {
  opacity: 0.7;
  filter: alpha(opacity=0);
}
.test3 {
  opacity: 0;
  filter: alpha(opacity=0);
}
# 

opacity is OK
filter is not OK

Thanks for this very useful tool !

**Comment by anointed** [comment]
Having the same issue

**Comment by marklagendijk** [comment]
This is a less.js issue and not an WinLess issue.

I'm not sure what causes this issue exactly, but it does work if we use both string interpolation and value escaping:

``` css
.opacity(@op){
opacity:@op/100;
filter: ~"alpha(opacity=@{op})";
}

.test0 {
.opacity(0);
}

.test1 {
.opacity(90);
}

.test2 {
.opacity(70);
}

.test3 {
.opacity(0);
}
```
